"""
HawkEye SOC — Root Cause ML Module
====================================
RandomForest-based root-cause classification for correlated incidents.

Modules
-------
feature_engineering.py : Raw alert rows -> fixed-width feature vectors.
train_model.py          : Training pipeline (CLI + programmatic ``train()``).
evaluate.py              : Standalone / reusable evaluation utilities.
predictor.py             : Inference — ``load_model()`` / ``predict_root_cause()``.

Integration note: this __init__.py was added during backend integration
so the package is importable as ``app.ml``. The individual modules use
``sys.path.insert(0, str(Path(__file__).parent))`` plus plain (non-relative)
local imports (e.g. ``from feature_engineering import ...``) — this was
left exactly as authored, since it works correctly regardless of package
context and rewriting it would touch business logic. No logic was added,
removed, or changed.

The trained model artefact is expected at ``app/ml/root_cause_model.pkl``
(generated by running ``train_model.py``; not included in this repo).
"""

from .feature_engineering import FEATURE_COLUMNS, engineer_features, build_feature_row
from .predictor import load_model, predict_root_cause, predict_with_probabilities

__all__ = [
    "FEATURE_COLUMNS",
    "engineer_features",
    "build_feature_row",
    "load_model",
    "predict_root_cause",
    "predict_with_probabilities",
]
